# Generated by Django 4.2.8 on 2023-12-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('portfolio_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
